"""empty message

Revision ID: 7c58edf12441
Revises: 0895e1b57934
Create Date: 2021-05-31 14:56:05.084070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c58edf12441'
down_revision = '0895e1b57934'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('language_1', sa.String(), nullable=True))
    op.drop_column('post', 'english')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('english', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('post', 'language_1')
    # ### end Alembic commands ###
