"""empty message

Revision ID: 8633e1013011
Revises: 7c58edf12441
Create Date: 2021-06-01 15:37:00.854069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8633e1013011'
down_revision = '7c58edf12441'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('post', sa.Column('language_2', sa.String(), nullable=True))
    op.add_column('post', sa.Column('language_3', sa.String(), nullable=True))
    op.add_column('post', sa.Column('post_image_url', sa.String(), nullable=True))
    op.add_column('post', sa.Column('post_date_time', sa.DateTime(), nullable=True))
    op.add_column('post', sa.Column('theme_id', sa.Integer(), nullable=True))
    op.add_column('post', sa.Column('country_id', sa.Integer(), nullable=True))
    op.add_column('post', sa.Column('post_status_id', sa.Integer(), nullable=True))
    op.add_column('post', sa.Column('post_type_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'post', 'theme', ['theme_id'], ['id'])
    op.create_foreign_key(None, 'post', 'country', ['country_id'], ['id'])
    op.create_foreign_key(None, 'post', 'post_status', ['post_status_id'], ['id'])
    op.create_foreign_key(None, 'post', 'post_type', ['post_type_id'], ['id'])
    op.drop_column('post', 'post_type')
    op.drop_column('post', 'kirundi')
    op.drop_column('post', 'french')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('french', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('post', sa.Column('kirundi', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('post', sa.Column('post_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_column('post', 'post_type_id')
    op.drop_column('post', 'post_status_id')
    op.drop_column('post', 'country_id')
    op.drop_column('post', 'theme_id')
    op.drop_column('post', 'post_date_time')
    op.drop_column('post', 'post_image_url')
    op.drop_column('post', 'language_3')
    op.drop_column('post', 'language_2')
    op.drop_table('post_type')
    op.drop_table('post_status')
    # ### end Alembic commands ###
