"""empty message

Revision ID: 9ddff339b4b2
Revises: 1c46b21b7854
Create Date: 2021-05-29 14:05:42.423712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ddff339b4b2'
down_revision = '1c46b21b7854'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('country', sa.Column('code', sa.String(length=3), nullable=True))
    op.add_column('country', sa.Column('status', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'country', ['code'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'country', type_='unique')
    op.drop_column('country', 'status')
    op.drop_column('country', 'code')
    # ### end Alembic commands ###
